ARG BASE_CONTAINER=jupyter/scipy-notebook
FROM $BASE_CONTAINER

LABEL maintainer="Robinsson Deantonio <rysanchezd@unal.edu.co>"

USER root

# ffmpeg for matplotlib anim & dvipng+cm-super for latex labels
RUN apt-get update --yes && \
    apt-get install --yes build-essential libzbar-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/* 

# Install ExifTool
COPY Image-ExifTool-12.28 ./Image-ExifTool-12.28
RUN cd $HOME/Image-ExifTool-12.28 && \
    perl Makefile.PL && \
    make install && \
    cd .. && \
    rm -rf Image-ExifTool-12.28

USER ${NB_UID}

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt


